---
title: "Marianadin"
author: "Esteban Marianadin"
format: html
---

```{r}
library(here)
library(ggplot2)
library(tidyr)
library(dplyr)
library(vroom)
library(knitr)
```

```{r}
here::i_am("test-grades.Rproj")
```

# Introduction 

### Question 1

```{r}
courses <- vroom(here("data", "courses.csv"))
```

### Question 2

```{r}

courses |>
  arrange(course) |>
  rename(
    `course name`      = course,
    identifier         = course_id,
    semester           = semester,
    `number of grades` = nb_grades
  ) |>
  knitr::kable()

```

### Question 3

```{r}
library(vroom)

students <- vroom(here("data", "students.csv"),
  col_types = cols(
    id = col_integer(),
    group = col_factor(),
    birth_date = col_date(),
    sex = col_factor()
  )
)

```

The `birth_date` column of the `students` data frame is of class `r class(students$birth_date)`. The `sex` column is of class `r class(students$sex)`.


### Question 4

```{r}
library(vroom)

grades <- vroom(here("data","grades.csv"),
  delim = ":",
  na = "unknown",
  col_types = cols(
    id = col_integer(),
    course_id = col_integer(),
    grade = col_double()
  )
)

```




# Student population analysis





